### ISSUE TITLE
lolApi.league("/by-summoner/REQUIRED_SUMMONER_ID/entry")

### ISSUE THREAD

**Issue by rdrnt** [moov2/lolAPIWrapper#5]
When trying to use `lolApi.league("/by-summoner/REQUIRED_SUMMONER_ID/entry")` the following issue occurs. For some reason its calling:
`https://global.api.pvp.net/api/lol/static-data/na/v2.5/league/by-summoner/48050102/entry?api_key=APIKEYHERE`

when It should be calling:
`https://na.api.pvp.net/api/lol/na/v2.5/league/by-summoner/48050102/entry?api_key=APIKEYHERE`

Maybe I'm going mad, does this occur for anybody else?

**Comment by mobinzk** [comment]
Hey @rdrnt,
I just pushed a new update (v1.1.7) that should resolve your problem.

Let me know if you still having problem.
