### ISSUE TITLE
Versions Static Data

### ISSUE THREAD

**Issue by calebmanley** [moov2/lolAPIWrapper#7]
Getting this error when trying to grab "/versions" from the static data.
`Could not cast value of type '__NSArrayM' (0x100f7fb60) to 'NSDictionary' (0x100f7ffe8).`

For example... `api.lol_static_data("/versions").get()`
Probably a little oversight there..!

**Comment by MatrixSenpai** [comment]
Try using my fork to get a more distinct error. Place a breakpoint in the delegate function errorDidOccur and post what it prints, including the URL it prints. Make sure to use the APIWithDebug func instead of APIKey provided in this version

**Comment by calebmanley** [comment]
Thanks I'll do that. But your get function still returns an NSDictionary. I'm pretty sure the problem is that the [versions static data](https://developer.riotgames.com/api/methods#!/1055/3630) file is a list of strings, not a dictionary. Which is why it can't cast it to an NSDictionary. I'll get back to you though.

**Comment by MatrixSenpai** [comment]
I'll check that and get back to you, however any data that's been passed back should be in JSON format, which should be by default a dictionary (even if it doesn't appear that way). I'll have to do a little more digging, but it shouldn't be trying to cast as an array

**Comment by calebmanley** [comment]
Your fork just breaks everything for me. I've had to remove the shared instance as it was just causing a straight up crash. Now it is telling me URL's are invalid even though all I've done is changed over to your fork.

**Comment by MatrixSenpai** [comment]
That makes no sense. I'm using it in an app under development right now and it's working just fine. What errors is Xcode outputting? Did you try just copying the raw API file instead of installing via CocoaPods?

**Comment by calebmanley** [comment]
I copied the raw API file, I don't use CocoaPods.

I found the main issue.
In genURL you've messed up this part: ((static_data) ? APIURL : STATICAL)
I switched it around now it works for me!

The shared instance still causes a crash though. I think it is endlessly creating instances.
In the debug navigator its calling thousands of lolApiWrapper.init()

**Comment by calebmanley** [comment]
I copied the raw API file, I don't use CocoaPods.

I found the main issue.
In genURL you've messed up this part: ((static_data) ? APIURL : STATICAL)
Classic mistake, I switched it around now it works for me!

The shared instance still causes a crash though. I think it is endlessly creating instances.
In the debug navigator its calling thousands of lolApiWrapper.init()

**Comment by calebmanley** [comment]
Still, the problem is I can't get the static data versions.
It's giving me this error: Could not cast value of type '__NSArrayM' to 'NSDictionary'
When calling: api.lol_static_data("/versions").get()

I put a break point at urlToRequest in getJSON (the function that it crashes in) and the url it is returning is the right URL for the versions JSON file.

**Comment by MatrixSenpai** [comment]
I'll take a look at it when I get home tonight, make some updates and try to push

**Comment by MatrixSenpai** [comment]
Updated the wrapper to solve the multiple shared instances. I forgot all about the APIKey function and was treating it as an initializer (which it should have been in the first place >.>). I'm looking further into the static data

**Comment by MatrixSenpai** [comment]
Wow, okay. I didn't realize that every single function returns an instance of the LolAPIWrapper. These will have to be rewritten. I'll also try to finish a couple of the API wrappers as well

**Comment by MatrixSenpai** [comment]
Okay, I give up lol. I'm probably just going to write my own. I'll comment with a link when it's done. This project is extremely unfinished and it doesn't seem as the original developer is maintaining it

**Comment by mobinzk** [comment]
@calebmanley This been fixed in version 1.1.8.
